CORE = sa1

VSRC = address.v cheat.v clk_test.v dac.v dcm.v sa1.v main.v mcu_cmd.v msu.v sd_dma.v spi.v
VHSRC =

XIL_IP = dec_table sa1_div sa1_iram sa1_mult snescmd_buf
XIL_IPCORE_DIR = ipcore_dir

include ../settings.mk
include ../common.mk
