CORE = test

VSRC = address.v clk_test.v dac.v dcm.v main.v mcu_cmd.v sd_dma.v spi.v
VHSRC =

COMMON_IP = dac_buf PA bram

XIL_IP =
XIL_IPCORE_DIR = ipcore_dir

INT_IP = pll

include ../settings.mk
include ../common.mk
