CORE = sdd1

VSRC = address.v cheat.v clk_test.v dac.v DCM_Scope.v main.v mcu_cmd.v msu.v sd_dma.v spi.v
VHSRC = FIFO_B2B.vhd FIFO_AXIS.vhd Golomb_0_Decoder.vhd Golomb_N_Decoder.vhd Input_Manager.vhd Output_Manager.vhd Probability_Estimator.vhd SDD1.vhd Serializer.vhd

XIL_IP = dac_buf msu_databuf snescmd_buf
XIL_IPCORE_DIR = ipcore_dir

include ../settings.mk
include ../common.mk
