CORE = obc1

VSRC = address.v cheat.v clk_test.v dac.v dcm.v obc1.v main.v mcu_cmd.v msu.v sd_dma.v spi.v
VHSRC =

XIL_IP = dac_buf msu_databuf obc_lower obc_upper snescmd_buf
XIL_IPCORE_DIR = ipcore_dir

include ../settings.mk
include ../common.mk
