CORE = obc1

VSRC = address.v cheat.v clk_test.v dac.v dcm.v obc1.v main.v mcu_cmd.v msu.v regshadow.v sd_dma.v spi.v
VHSRC =

COMMON_IP = dac_buf msu_databuf obc_lower obc_upper snescmd_buf

XIL_IP =
XIL_IPCORE_DIR = ip/mk2

INT_IP = pll

include ../settings.mk
include ../common.mk
