CORE = sgb

VSRC = address.v cheat.v clk_test.v dac.v dcm.v main.v mcu_cmd.v msu.v sd_dma.v spi.v sgb.v sgb_cpu.v sgb_icd2.v
VHSRC =

COMMON_IP = dec_table vram oam hram row_buf msu_databuf dac_buf snescmd_buf

XIL_IP =
XIL_IPCORE_DIR = ipcore_dir

INT_IP = pll

include ../settings.mk
include ../common.mk
