CORE = cx4

VSRC = address.v cheat.v clk_test.v dac.v dcm.v cx4.v main.v mcu_cmd.v msu.v sd_dma.v spi.v
VHSRC =

XIL_IP = cx4_datram cx4_datrom cx4_mul cx4_pgmrom dac_buf msu_databuf snescmd_buf
XIL_IPCORE_DIR = ipcore_dir

include ../settings.mk
include ../common.mk
