CORE = base

VSRC = address.v cheat.v clk_test.v dac.v dcm.v bsx.v rtc.v srtc.v main.v mcu_cmd.v msu.v sd_dma.v spi.v
VHSRC =

XIL_IP = dac_buf msu_databuf snescmd_buf
XIL_IPCORE_DIR = ipcore_dir

include ../settings.mk
include ../common.mk
