CORE = base

VSRC = address.v cheat.v clk_test.v dac.v dcm.v bsx.v rtc.v srtc.v main.v mcu_cmd.v msu.v sd_dma.v spi.v
VHSRC =

COMMON_IP = dac_buf msu_databuf snescmd_buf

HEADER = config.vh

XIL_IP =
XIL_IPCORE_DIR = ipcore_dir

INT_IP = pll

include ../settings.mk
include ../common.mk
