CORE = gsu

VSRC = address.v cheat.v dac.v dcm.v gsu.v main.v mcu_cmd.v msu.v sd_dma.v spi.v
VHSRC =

XIL_IP = dac_buf gsu_cache gsu_fmult gsu_mult gsu_umult msu_databuf snescmd_buf
XIL_IPCORE_DIR = ipcore_dir

include ../settings.mk
include ../common.mk
