#ifndef _CONFIG_H
#define _CONFIG_H

#define SDCARD_DETECT		(1)
#define SDCARD_WP		(0)
#define SD_SUPPLY_VOLTAGE	(1L<<21) /* 3.3V - 3.4V */
#define CONFIG_SD_BLOCKTRANSFER 1
#define CONFIG_SD_AUTO_RETRIES	10
#define CONFIG_SD_DATACRC	1


#define CONFIG_UART_NUM			3
#define CONFIG_CPU_FREQUENCY		90315789
#define CONFIG_UART_PCLKDIV		1
#define CONFIG_UART_TX_BUF_SHIFT	5
#define CONFIG_UART_BAUDRATE		921600
#define CONFIG_UART_DEADLOCKABLE
#endif
