#ifndef _CONFIG_H
#define _CONFIG_H

#define CONFIG_UART_NUM			3
#define CONFIG_CPU_FREQUENCY		90315789
#define CONFIG_UART_PCLKDIV		1
#define CONFIG_UART_TX_BUF_SHIFT	7
#define CONFIG_UART_BAUDRATE		115200

#endif
