#ifndef MSU1_H
#define MSU1_H

#ifdef DEBUG_MSU1
#define DBG_MSU1
#else
#define DBG_MSU1 while(0)
#endif

#define MSU_FPGA_STATUS_SD_DMA_BUSY 0x8000
#define MSU_FPGA_STATUS_DAC_READ_MSB 0x4000
#define MSU_FPGA_STATUS_MSU_READ_MSB 0x2000
#define MSU_FPGA_STATUS_AUDIO_START 0x40
#define MSU_FPGA_STATUS_DATA_START 0x20
#define MSU_FPGA_STATUS_CTRL_START 0x01

#define MSU_FPGA_STATUS_CTRL_RESUME_FLAG_BIT 0x8
#define MSU_FPGA_STATUS_CTRL_REPEAT_FLAG_BIT 0x4
#define MSU_FPGA_STATUS_CTRL_PLAY_FLAG_BIT 0x2

#define MSU_DAC_BUFSIZE	(2048)

int msu1_check(uint8_t*);
int msu1_loop(void);

#endif
